"""Restore required literal labels in Claude output and export human review material.

Endpoint wording is never rewritten. The raw generation remains immutable.
"""
import argparse
import json
import re
from pathlib import Path

from engine.prompt_assembly import load_template
from engine.validity_sweep import digest, verify_record
from engine.validity_variants import PARAMETER_RE, validate_paraphrase
from run_validity_claude import save_new


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-record', required=True, type=Path)
    parser.add_argument('--out', required=True, type=Path)
    args = parser.parse_args()
    record = json.loads(args.source_record.read_text(encoding='utf-8'))
    verify_record(record)
    if record.get('error_message') or not record.get('model_version', '').startswith('claude-'):
        raise ValueError('Require a returned Claude generation')
    raw = record['raw_response'].strip()
    if raw.startswith('```'):
        raw = re.sub(r'^```(?:json)?\s*|\s*```$', '', raw)
    generated = json.loads(raw)
    if len(generated.get('variants', [])) != 3:
        raise ValueError('Expected three variants')
    canonical = load_template()
    reference = list(PARAMETER_RE.finditer(canonical))
    headings = re.findall(r'^# .*', canonical, re.M)
    variants = []
    review = ['# Phase 1.5 paraphrases: human semantic review required', '',
              'These three templates were generated by '+record['model_version']+'.',
              'Only section headings and parameter names were restored to required literal labels.',
              'Endpoint wording below is unchanged from Claude. No human approval is claimed.',
              'Review whether every low/high meaning and direction is preserved, including qualifiers.', '']
    for index, item in enumerate(generated['variants'], 1):
        template = item['template']
        old_headings = re.findall(r'^# .*', template, re.M)
        matches = list(PARAMETER_RE.finditer(template))
        if len(old_headings) != 3 or len(matches) != 10:
            raise ValueError('Unexpected template structure')
        edits = []
        for old, ref in zip(matches, reference):
            if old[1] != ref[1] or old[3] != ref[3]:
                raise ValueError('Number or placeholder differs; cannot restore mechanically')
            edits.append((old.start(2), old.end(2), ref[2]))
        for start, end, replacement in reversed(edits):
            template = template[:start]+replacement+template[end:]
        for old, expected in zip(old_headings, headings):
            template = re.sub('^'+re.escape(old)+'$', lambda _: expected, template, count=1, flags=re.M)
        checks = validate_paraphrase(template)
        if not checks['lexical_target_met']:
            raise ValueError('Lexical target not met; do not approve this bundle')
        restored = list(PARAMETER_RE.finditer(template))
        assert [(m[4], m[5]) for m in matches] == [(m[4], m[5]) for m in restored]
        variants.append({'template': template, 'generator_model': record['model_version'],
                         'checks': checks, 'human_review': {'approved': False, 'reviewer': None,
                         'template_hash': checks['template_hash']}})
        review.extend([f'## Variant {index}', '', f'Template hash: `{checks["template_hash"]}`', ''])
        for ref, alt in zip(reference, restored):
            review.extend([f'### {ref[2]}', '', f'- Canonical 0: {ref[4]}',
                           f'- Candidate 0: {alt[4]}', f'- Canonical 1: {ref[5]}',
                           f'- Candidate 1: {alt[5]}', ''])
        review.extend(['Full candidate template:', '', '```text', template, '```', ''])
    bundle = {'variants': variants, 'provenance': {
        'source_record': str(args.source_record.resolve()), 'source_record_hash': record['record_hash'],
        'normalization': 'Restore only literal headings and parameter names by verified position; endpoints unchanged',
        'canonical_hash': digest(canonical)}}
    save_new(args.out/'paraphrases_for_review.json', bundle)
    target = args.out/'HUMAN_REVIEW.md'
    content = '\n'.join(review)
    if target.exists():
        if target.read_text(encoding='utf-8') != content:
            raise ValueError('Existing review differs')
    else:
        target.write_text(content, encoding='utf-8')
    print(f'Three structurally valid candidates, all lexical checks passed: {target}')


if __name__ == '__main__':
    main()
