"""Recover the explicit corrected_variants field without modifying generated text."""
import argparse
import json
import re
from pathlib import Path

import utils
from engine.validity_sweep import ValiditySink, digest
from engine.validity_variants import PARAMETER_RE, validate_paraphrase
from generate_validity_endpoint_paraphrases import assemble
from run_validity_claude import save_new


def main(root):
    request=json.loads((root/'generation_request.json').read_text(encoding='utf-8'))
    row=next(ValiditySink(root/'records').read_all())
    if row.get('error_message') or row['model_version']!='claude-haiku-4-5-20251001':
        raise ValueError('Require successful exact-model response')
    parsed=json.loads(re.sub(r'^```(?:json)?\s*|\s*```$', '', row['raw_response'].strip()))
    corrected=parsed['corrected_variants']
    prior=request['previous_candidates']['variants']
    if len(corrected)!=3 or len(prior)!=3:
        raise ValueError('Require three candidates')
    changes=[]
    for number,(old,new) in enumerate(zip(prior,corrected),1):
        for code,pair in old['endpoints'].items():
            for pole,text in pair.items():
                if new['endpoints'][code][pole]!=text:
                    changes.append((number,code,pole))
    expected=[(e['variant'],e['parameter'],e['endpoint']) for e in request['corrections']]
    if set(changes)!=set(expected):
        raise ValueError('Actual corrections differ from requested endpoint set')
    canonical=request['canonical_template']; variants=[]
    lines=['# Final paraphrase candidates — human review pending', '',
        'All endpoint wording was generated by Claude Haiku 4.5 following assistant semantic feedback.',
        'No behavioural outcomes informed generation or selection. All non-endpoint text is canonical.',
        'The final response used corrected_variants instead of variants; extraction changes no words.',
        'Assistant review recommends all three for human review, not automatic experimental approval.', '',
        'Review the low/high meanings and directions below. Approve variants 1–3 by these hashes,',
        'with your reviewer name, or identify wording to revise. Approval here authorises semantic',
        'use of these exact templates; the existing 4,500-call design remains unchanged.', '']
    for number,candidate in enumerate(corrected,1):
        template=assemble(candidate['endpoints'],canonical)
        checks=validate_paraphrase(template,canonical)
        if not checks['lexical_target_met']:
            raise ValueError('Lexical criterion not met')
        variants.append({'template':template,'generator_model':row['model_version'],'checks':checks,
            'human_review':{'approved':False,'reviewer':None,'template_hash':checks['template_hash']}})
        lines.extend([f'## Variant {number}', '', f'Exact template hash: `{checks["template_hash"]}`', '',
            '| Parameter | Canonical 0 | Candidate 0 | Canonical 1 | Candidate 1 |',
            '|---|---|---|---|---|'])
        for code,stanza in zip(utils.PARAM_NAMES,PARAMETER_RE.finditer(canonical)):
            pair=candidate['endpoints'][code]
            lines.append(f'| {code} | {stanza[4]} | {pair["0"]} | {stanza[5]} | {pair["1"]} |')
        lines.extend(['', '<details><summary>Full exact template</summary>', '', '```text',template,'```','</details>',''])
    save_new(root/'paraphrases_for_review.json',{'variants':variants,'provenance':{
        'source_record_hash':row['record_hash'],'construction':'Extract corrected_variants; substitute endpoints only; no generated wording edited',
        'verified_changed_endpoints':changes,'human_approval_pending':True}})
    content='\n'.join(lines)
    p=root/'HUMAN_REVIEW.md'
    if p.exists() and p.read_text(encoding='utf-8')!=content:
        raise ValueError('Existing review differs')
    p.write_text(content,encoding='utf-8')
    print(json.dumps({'review':str(p),'hashes':[v['checks']['template_hash'] for v in variants],
        'lexical_checks':[v['checks']['jaccard_by_parameter'] for v in variants]},indent=2))


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--run-root',type=Path,required=True)
    main(p.parse_args().run_root)
