import contextlib
import copy
import io
import json
from pathlib import Path
import sys
import tempfile
import unittest
import zipfile

sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'code'))
import phase4_consequence_rule_pilot as study
from phase3_budget import BudgetStop,digest,read_checked
from phase3_representation_diagnostic import profile_parts,numeric_rows,prose_rows
from phase4_consequence_tasks import TASK_IDS,task,transition,mapping
from phase4_finite_rules import score


class FiniteRulePilot(unittest.TestCase):
    @classmethod
    def setUpClass(cls):cls.pop=study.Population.draw(6,seed=study.SEED).to_dict()

    def test_all_twelve_action_vectors(self):
        # Independent authored expected outcomes, not generated by the rule formulas.
        disclosure={'report':([0,0,0,0,1,1,1,1],[1,1,1,1]),
            'falsify':([0,1,1,1,0,0,0,0],[0,0,1,1]),
            'skip':([0,1,1,1,0,0,0,0],[0,0,1,1])}
        allocation={'equal':([0,0,0,0,1,0,1,0],[1,1,1,1]),
            'unequal':([0,0,0,1,0,0,1,0],[1,1,1,0]),
            'skip':([0,0,1,1,0,0,0,0],[0,1,1,1])}
        count=0
        for t in TASK_IDS:
            expected=copy.deepcopy(disclosure if t.startswith('disclosure') else allocation)
            if t=='disclosure_12':expected['report'][0][2]=1
            for a,(r,f) in expected.items():
                actual=score(t,a);count+=1
                self.assertEqual(actual['configuration_relative'],r)
                self.assertEqual(actual['fixed_standard'],f)
                e=actual['effects'];self.assertEqual(e['total_delta'],e['actor_delta']+sum(e['third_party_deltas']))
        self.assertEqual(count,12)
        high=score('disclosure_12','report')['headlines']
        self.assertEqual((high['relative_headline'],high['fixed_headline']),('not_good','good'))
        self.assertEqual(high['net_score_bounds'],[3,3]);self.assertEqual(high['weighted_score_bounds'],[2.5,2.5])
        self.assertEqual(score('allocation_12','unequal')['headlines']['weighted_possible'],['neutral'])
        with self.assertRaises(ValueError):score('invented','report')
        with self.assertRaises(ValueError):score('disclosure_2','invented')

    def test_schedule_controls_cost_and_mapping(self):
        original=copy.deepcopy(self.pop);batch=study.schedule(self.pop)
        self.assertEqual(len(batch),97);self.assertEqual(len({j['slot'] for j in batch}),97)
        self.assertLessEqual(sum(j['reserved_nano'] for j in batch)+study.PRIOR,study.CAP)
        for t in TASK_IDS:
            for a in task(t)['actions']:
                for label in 'ABC':self.assertEqual(sum(mapping(t,i)[label]==a for i in range(1,7)),2)
        for agent in self.pop['agents']:
            p=agent['parameters'];pe,be,se=profile_parts(study.system(p,'E'));pv,bv,sv=profile_parts(study.system(p,'V'))
            self.assertEqual((pe,se),(pv,sv));self.assertEqual(numeric_rows(be),prose_rows(bv))
            for a in ('U','G'):self.assertEqual(study.system(p,a),study.system(self.pop['agents'][0]['parameters'],a))
        self.assertEqual(original,self.pop)

    def test_analysis_missingness_and_duplicates(self):
        rows=[{**j['cell'],'action':next(iter(task(j['cell']['task'])['actions']))} for j in study.participant_jobs(self.pop)]
        result=study.analyze(rows,6);self.assertEqual(result['valid'],96)
        self.assertTrue(all(x['estimate']==0 for v in result['contrasts'].values() for x in v.values()))
        high=next(c for c in result['cells'] if c['task']=='disclosure_12' and c['arm']=='E')
        self.assertEqual(high['headline_rate_bounds']['relative']['not_good'],[1,1])
        self.assertEqual(high['headline_rate_bounds']['fixed']['good'],[1,1])
        rows[0]['action']=None;result=study.analyze(rows,6)
        self.assertEqual(result['valid'],95)
        target=next(c for c in result['cells'] if (c['task'],c['arm'])==(rows[0]['task'],rows[0]['arm']))
        self.assertEqual(target['missing'],1)
        self.assertLess(*target['total_delta_identification_bounds'])
        self.assertEqual(target['category_one_rate_bounds']['coercion_avoidance'],[1,1])
        with self.assertRaises(BudgetStop):study.analyze(rows[:-1],6)
        with self.assertRaises(BudgetStop):study.analyze(rows+[rows[0]],6)
        for bad in ('{"choice":"A","choice":"B"}','{"choice":true}','{"choice":[]}','{"choice":"D"}'):
            self.assertIsNone(study.choice(bad,{'A':'report','B':'skip','C':'falsify'}))

    def fixture(self,tmp):
        root,folder=Path(tmp)/'ledger',Path(tmp)/'study'
        with zipfile.ZipFile(study.ROOT/read_checked(study.PARENT/'CHECKPOINT.json')['archive']) as z:z.extractall(root)
        release=read_checked(study.FOLDER/'release.json');pop=copy.deepcopy(self.pop)
        pop['agents']=pop['agents'][:1];pop['n_agents']=1;batch=study.schedule(pop)
        release['slots']={j['slot']:{**release['slots'][j['slot']],'request_sha256':digest(j['request'])} for j in batch}
        release['population_sha256']=digest(pop);release['jobs_sha256']=digest(batch)
        return root,folder,(release,pop,batch)

    def raw(self,req,text):
        if req['model']==study.JUDGE:
            return {'model':req['model'],'usage':{'input_tokens':100,'output_tokens':40},
                'stop_reason':'end_turn','content':[{'type':'text','text':text}]}
        return {'model':req['model'],'usage':{'prompt_tokens':100,'completion_tokens':20},
            'choices':[{'finish_reason':'stop','message':{'content':text}}]}

    def test_full_mock_and_zero_call_replay(self):
        with tempfile.TemporaryDirectory() as tmp,contextlib.redirect_stdout(io.StringIO()):
            root,folder,data=self.fixture(tmp);calls=[]
            def mock(req):
                calls.append(req)
                return self.raw(req,'{"verdict":"accept","blocking_issues":[],"limits":[]}' if len(calls)==1 else '{"choice":"A"}')
            r=study.collect(root=root,folder=folder,responder=mock,test_data=data)
            self.assertEqual(r['decision'],'pilot_complete');self.assertEqual(r['valid'],16);self.assertEqual(len(calls),17)
            self.assertEqual(study.collect(True,root,folder,lambda _:self.fail('Replay call'),data),r)
            for name,expected in data[0]['preserved_files'].items():self.assertEqual(study.sha(root/name),expected)
            changed=copy.deepcopy(data);changed[2][-1]['request']['temperature']=0
            with self.assertRaises(BudgetStop):study.collect(root=root,folder=folder,responder=mock,test_data=changed)

    def test_malformed_review_stops_before_participants(self):
        with tempfile.TemporaryDirectory() as tmp,contextlib.redirect_stdout(io.StringIO()):
            root,folder,data=self.fixture(tmp);calls=[]
            def invalid(req):
                calls.append(req);return self.raw(req,'{"verdict":"accept","blocking_issues":["Cannot accept"],"limits":[]}')
            r=study.collect(root=root,folder=folder,responder=invalid,test_data=data)
            self.assertEqual(r['participant_calls'],0);self.assertEqual(len(calls),1)
            self.assertEqual(r['review']['verdict'],'invalid')


if __name__=='__main__':unittest.main()
