const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pages=['welcome','rooms','profile','choices','findings'];
const pageNames=['Your field guide to PARIA','Inside the recorded study','Dispositions before decisions','Moral trade-offs in practice','The evidence and its boundaries'];
const arms={E:'Numeric profile',V:'Equivalent prose',U:'No profile',G:'Ethical guidance'};
const tourText=['Start with the idea: dispositions enter before the choice.','Inspect a recording. Press Play, then select an agent.','Move a coordinate. Read the endpoints before interpreting its value.','Choose an action, then compare all four recorded conditions.','Keep the positive findings and the unresolved claims together.'];
let data, world, active='welcome', chosen=null, tourIndex=null, toastTimer, room='C1-1-00100-E';
const values={};
function notice(text){$('#toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',3200);}
function navigate(id,focus=false){if(!pages.includes(id))id='welcome';active=id;$$('.page').forEach(p=>p.hidden=p.id!==id);$$('nav [data-page]').forEach(b=>b.setAttribute('aria-current',b.dataset.page===id?'page':'false'));$('#chapter-label').textContent=pageNames[pages.indexOf(id)];history.replaceState(null,'',`/explore#${id}`);if(id==='rooms'&&!$('#theatre').getAttribute('src'))openRoom(room);if(id==='welcome')world?.invalidate();if(focus){$('#content').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});} }
function openRoom(id){room=id;$('#theatre').src=`/lab?room=${encodeURIComponent(id)}#${id}`;$$('[data-room]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.room===id));}
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]'),r=e.target.closest('[data-room]');if(p){navigate(p.dataset.page,true);}if(r)openRoom(r.dataset.room);});
window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)));
$('#contrast').addEventListener('click',()=>{const on=document.body.classList.toggle('high-contrast');$('#contrast').setAttribute('aria-pressed',String(on));try{localStorage.setItem('paria-contrast',String(on));}catch{}});
try{if(localStorage.getItem('paria-contrast')==='true')$('#contrast').click();}catch{}
function updateTour(){if(tourIndex===null)return;$('#tour-bar').hidden=false;$('#tour-text').textContent=`${tourIndex+1} / 5 — ${tourText[tourIndex]}`;$('#tour-back').disabled=tourIndex===0;$('#tour-next').textContent=tourIndex===4?'Finish tour':'Next stop';navigate(pages[tourIndex],true);}
$('#tour').onclick=()=>{tourIndex=0;updateTour();};$('#tour-back').onclick=()=>{tourIndex=Math.max(0,tourIndex-1);updateTour();};$('#tour-next').onclick=()=>{if(tourIndex===4){$('#tour-bar').hidden=true;tourIndex=null;notice('Tour complete. Explore any chapter at your own pace.');}else{tourIndex++;updateTour();}};$('#tour-close').onclick=()=>{$('#tour-bar').hidden=true;tourIndex=null;};
function profileWords(){if(!data)return;$('#profile-words').innerHTML=data.parameters.map(p=>{const v=values[p.name];return `<p><b>${esc(p.label)} · ${v.toFixed(2)}</b><br>${v<.4?'Leans toward: '+esc(p.endpoint_0):v>.6?'Leans toward: '+esc(p.endpoint_1):'Between the two endpoints; no strong directional lean in this illustration.'}</p>`;}).join('');}
function buildProfile(){data.parameters.forEach(p=>values[p.name]=.5);$('#sliders').innerHTML=data.parameters.map(p=>`<div class="slider-card"><div class="slider-title"><label for="p-${p.name}">${esc(p.label)}<span>${esc(p.name)}</span></label><output for="p-${p.name}" id="out-${p.name}">0.50</output></div><input id="p-${p.name}" type="range" min="0" max="100" value="50" data-param="${p.name}" aria-describedby="ends-${p.name}"><div class="ends" id="ends-${p.name}"><span>0 · ${esc(p.endpoint_0)}</span><span>1 · ${esc(p.endpoint_1)}</span></div></div>`).join('');$('#sliders').addEventListener('input',e=>{if(!e.target.dataset.param)return;const key=e.target.dataset.param;values[key]=Number(e.target.value)/100;$(`#out-${key}`).value=values[key].toFixed(2);profileWords();});profileWords();}
$('#reset-profile').onclick=()=>{if(!data)return;data.parameters.forEach(p=>{values[p.name]=.5;$(`#p-${p.name}`).value=50;$(`#out-${p.name}`).value='0.50';});profileWords();};
$('#copy-profile').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify({type:'illustration_only',parameters:values},null,2));notice('Illustrative profile copied. No simulation was run.');}catch{notice('Clipboard unavailable. Your settings remain visible in the sliders.');}};
const titles={witness_cost:'The witness statement',safety_hold:'The safety decision'};
function dilemma(){if(!data)return;chosen=null;$('#choice-reveal').hidden=true;const key=$('#dilemma').value,t=data.tasks[key];$('#dilemma-title').textContent=titles[key];$('#situation').textContent=t.situation;$('#framing').textContent=data.framing;$('#options').innerHTML=Object.entries(t.actions).map(([id,a],i)=>`<button data-choice="${id}" aria-pressed="false"><strong>Option ${i+1}</strong>${esc(a.description)}<small>${esc(a.effect_text)}</small></button>`).join('');}
$('#dilemma').onchange=dilemma;
$('#options').onclick=e=>{const b=e.target.closest('[data-choice]');if(!b||!data)return;chosen=b.dataset.choice;$$('[data-choice]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.choice===chosen)));const a=data.tasks[$('#dilemma').value].actions[chosen];const flags=[['Harm avoidance',a.third_party_deltas.some(x=>x<0)],['Deception avoidance',a.deceptive],['Coercion avoidance',a.coercive],['Unfairness avoidance',a.unfair]];$('#consequences').innerHTML=`<b>Your choice: ${esc(a.description)}</b><p>${esc(a.effect_text)} Total simulated change: ${a.actor_delta+a.third_party_deltas.reduce((s,x)=>s+x,0)} units.</p><p>${flags.map(([label,violated])=>`${esc(label)}: <b>${violated?'violated':'upheld'}</b>`).join(' · ')}</p><p>This is a classification under the study’s assumptions, not an assessment of your character.</p>`;$('#choice-reveal').hidden=false;chart();};
function chart(){
 if(!data)return;
 const key=$('#dilemma').value,metric=$('#metric').value,replication=$('#study-version').value==='r3';
 const cells=replication?data.replication_cells:data.cells;
 $('#choice-chart').innerHTML=Object.entries(arms).map(([a,label])=>{
  const c=cells[`${key}/${a}`],v=c[metric];
  return `<div class="chart-row"><span>${label} <small>(${a}, n=${c.n_valid})</small></span><div class="bar-track" aria-hidden="true"><div class="bar" style="width:${100*v}%"></div></div><output>${(100*v).toFixed(1)}%</output></div>`;
 }).join('');
 $('#choice-finding').textContent=replication?(key==='witness_cost'?'Replication: +35.0 percentage points for E versus U; Holm p = 0.0004.':'Replication: +36.7 percentage points for E versus U; Holm p = 0.0006. The first study was null, so the result varies across samples.'):(key==='witness_cost'?'First study: +51.7 percentage points for E versus U on the net-score good rate; Holm p = 0.0002.':'First study: +3.3 percentage points for E versus U. The primary comparison showed no clear effect.');
}
const studySelect=document.createElement('label');studySelect.innerHTML='Recorded study<select id="study-version"><option value="r1">First study · 480 valid decisions</option><option value="r3">Replication · 956 of 960 valid</option></select>';
$('#metric').parentElement.before(studySelect);
$('#study-version').onchange=chart;
$('#metric').onchange=chart;
const updates=document.createElement('article');updates.className='note';updates.innerHTML='<b>New evidence · 16 September</b><p>The four-task replication found corrected E−U effects on witness (+35.0 points) and safety (+36.7 points), with four invalid responses retained. Switch between studies in Moral choices to see why a single run is not the whole story.</p><p>Three negative controls stayed unchanged across 720 decisions. On Haiku, the evidence-seal effect passed correction; three other contrasts were near ceilings. The magnitude sweep found sharp changes on two Sonnet tasks, while Haiku remained almost entirely fixed over the tested range.</p><p><strong>Interpretation remains bounded:</strong> the wording audit identified asymmetric cues in several stimuli. Increasing cost also increased harm, so the sweep does not isolate a mechanism. These results neither rank models morally nor demonstrate intrinsic ethical understanding.</p><p><a href="/sources/replication" target="_blank" rel="noopener">Replication</a> · <a href="/sources/specificity" target="_blank" rel="noopener">Controls</a> · <a href="/sources/model2" target="_blank" rel="noopener">Second model</a> · <a href="/sources/magnitude" target="_blank" rel="noopener">Magnitude sweep</a> · <a href="/sources/wording" target="_blank" rel="noopener">Wording audit</a></p>';
$('#findings .finding-grid').before(updates);
const glossary={'Encoded profile':'A set of ten disposition values supplied to the model before it generates a decision. It is an input intervention, not a claim about the model’s inner experience.','Information-matched prose':'The same disposition information expressed in words and percentages. It helps test whether the numerical format adds something distinctive.','Institutional configuration':'The HIGH or LOW settings of Freedom, Justice, Authority, Care and Loyalty. Phase 2 compares two bundled anchors; this does not isolate each axis.','Matched comparison':'The same sampled profiles or groups appear in each condition. The conversations remain separate. Matching improves comparability; it does not make all other uncertainties disappear.','Strict versus net scoring':'Strict relative scoring marks an action not_good if any negative category triggers. Net scoring subtracts negative category counts from positive ones. Neither convention is universal moral truth.','Baseline saturation':'A baseline repeatedly selects the same answer. This exposes a limit of the tested design, but encoded responses can still differ from that baseline.','Exploratory evidence':'An analysis that investigates patterns without turning discoveries into retrospectively confirmed predictions. New claims may need fresh, separately specified tests.','Verified replay':'Recorded requests and responses are checked against the original state transitions. Verification confirms faithful reconstruction, not the truth of an agent’s reasoning.'};
$('#glossary').innerHTML=Object.entries(glossary).map(([k,v])=>`<details><summary>${esc(k)}</summary><p>${esc(v)}</p></details>`).join('');
async function preview(){try{const [{World},response]=await Promise.all([import('/world.js'),fetch('/api/run/C1-1-00100-E')]);if(!response.ok)throw Error('Recording unavailable');const run=await response.json();await document.fonts.ready;world=new World($('#preview'),()=>navigate('rooms',true));await world.setRun(run);$('#preview .loading')?.remove();world.update(0,null,false);}catch{$('#preview').innerHTML='<p class="loading">The 3D preview needs WebGL and local recordings. You can still explore the profiles, moral choices and findings.</p>';}}
navigate(location.hash.slice(1));
(async()=>{try{const response=await fetch('/thesis-evidence.json');if(!response.ok)throw Error('Evidence file unavailable');data=await response.json();if(data.parameters.length!==10||!data.cells['witness_cost/E'])throw Error('Incomplete evidence export');buildProfile();dilemma();latestEvidence();}catch(e){$('#load-error').hidden=false;$('#load-error').textContent=`The evidence could not load: ${e.message}. Restart the local viewer server after building thesis-evidence.json.`;}})();
preview();
window.addEventListener('pagehide',()=>world?.dispose());

function latestEvidence(){
 if(!data?.latest)return;
 const panel=document.createElement('article');panel.className='latest-study';panel.id='latest-study';
 panel.innerHTML=`<span class="pill">Central moral experiment · 16 September</span><h2>Same situations. Different dispositions.</h2><p>Across six screened situations, numeric profiles produced more choices classified as good under the study’s net rule than ethical guidance did. Explore the pooled result, then check how much the individual situations differ.</p><label>Compare results<select id="latest-view"><option value="pooled">All six situations</option>${Object.keys(data.latest.per_item).map(k=>`<option value="${k}">${esc(k.replaceAll('_',' '))}</option>`).join('')}</select></label><div id="latest-chart" class="chart" aria-live="polite"></div><p id="latest-detail"></p><p class="caption">40 profiled agents, one model. Repeated choices across six situations are not 240 independent situations. “Good” is a stipulated classification, not demonstrated moral improvement. This guidance control is not the information-matched prose control.</p><a href="/sources/phase4b" target="_blank" rel="noopener">Read the primary study and its limits</a> · <a href="/sources/grand" target="_blank" rel="noopener">Explore the three-model background study</a>`;
 $('#findings .section-top').after(panel);
 function draw(){const key=$('#latest-view').value,a=data.latest;
 if(key==='pooled'){
 $('#latest-chart').innerHTML=['U','G','E'].map(k=>{const c=a.cells.all[k];return `<div class="chart-row"><span>${arms[k]} <small>(n=${c.n})</small></span><div class="bar-track" aria-hidden="true"><div class="bar" style="width:${100*c.good_rate}%"></div></div><output>${(100*c.good_rate).toFixed(1)}%</output></div>`;}).join('');
 $('#latest-detail').textContent='Paired profile versus guidance difference: +17.1 percentage points; pooled Holm p = 0.000112. Four of six items point in the positive direction. Guidance versus the unprofiled baseline was inconclusive, not proven ineffective.';
 }else{const c=a.per_item[key];$('#latest-chart').innerHTML=`<div class="item-effect"><strong>${c.effect>0?'+':''}${(100*c.effect).toFixed(1)}<small>percentage points</small></strong><p>Numeric profile minus ethical guidance<br>${c.pairs} matched agent pairs</p></div>`;$('#latest-detail').textContent=`Holm-adjusted p = ${a.holm['item:'+key]}. ${a.holm['item:'+key]<.05?'This item passed the stated correction.':'This item did not establish a clear difference.'} The complete item set includes both positive and negative estimates.`;}}
 $('#latest-view').onchange=draw;draw();
 const callout=document.createElement('div');callout.className='note';callout.innerHTML='<b>New chapter: the central moral experiment</b><p>Profiles versus guidance, six situations, and a result you can inspect item by item.</p><button data-page="findings">Explore the latest findings</button>';$('#welcome .trail').before(callout);
}

